[project]
name = "ros-python-conversions"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "data-models",
    "rosidl-runtime-py",
    "scipy>=1.7.0",
]

[tool.setuptools.packages.find]
where = ["src"]

